### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Shundere** [AsteriskAmpersand/MHW_Gerardo_Fix#1]
Makes you spawn in a grey void on start up and you start falling after a few seconds.
You can warp before that but the NPC for the quest aren't there and warping to the research base crashes the game.

**Comment by bibbybutt** [comment]
Having the same issue

**Comment by PogopunkXIII** [comment]
Have the same issue

**Comment by AsteriskAmpersand** [comment]
Try saving in the research base before applying the fix if that doesn't work try saving in Astera before applying the fix.

**Comment by PogopunkXIII** [comment]
I had tried saving in the research base, will try astera now.

**Comment by PogopunkXIII** [comment]
saved in astera, followed the readme, got the same exact outcome. Grey void, fast travelling to the research base causes a crash.

**Comment by Synntechgaming** [comment]
So when I applied the "fix" im just in a grey skybox continuously falling. I cant do anything. I couldnt revert back to my old save game. So i guess i just lost my 1k hour character? 😭

**Comment by Shundere** [comment]
> saved in astera, followed the readme, got the same exact outcome. Grey void, fast travelling to the research base causes a crash.

same here, neither worked.

**Comment by Shundere** [comment]
> So when I applied the "fix" im just in a grey skybox continuously falling. I cant do anything. I couldnt revert back to my old save game. So i guess i just lost my 1k hour character? 😭

You might be able to warp right as you spawn. Of course, going to the research base will probably crash the game and whatever the "fix" muddled with will be wrecked unless they make something to revert whatever their "fix" breakes.

**Comment by Synntechgaming** [comment]
> You might be able to warp right as you spawn. 

Yeah just tried I was able to quickly fast travel to research base but I got the crash. I hope they can some how fix it cause I really don't want to lose all my progress on that character. Spent so much time on it. RIP. 😭

**Comment by PogopunkXIII** [comment]
OK I have the fix:

* Save in research base, close the game
* backup `SAVEDATA1000`
* Open `SAVEDATA1000` in the save editor
* Save file as unencrypted (.bin)
* Drag and drop unencrypted save file on `GeraltFix.exe`
* Open `Fix.bin` in the save editor
* Save as encrypted over the original `SAVEDATA1000` 
* launch game and talk to geralt

**Comment by Shundere** [comment]
> OK I have the fix:
> 
> * Save in research base, close the game
> * backup `SAVEDATA1000`
> * Open `SAVEDATA1000` in the save editor
> * Save file as unencrypted (.bin)
> * Drag and drop unencrypted save file on `GeraltFix.exe`
> * Open `Fix.bin` in the save editor
> * Save as encrypted over the original `SAVEDATA1000`
> * launch game and talk to geralt

THAT WORKED! Thank you sooo much!

**Comment by Synntechgaming** [comment]
> OK I have the fix:

Save in research base, close the game
backup SAVEDATA1000
Open SAVEDATA1000 in the save editor
Save file as unencrypted (.bin)
Drag and drop unencrypted save file on GeraltFix.exe
Open Fix.bin in the save editor
Save as encrypted over the original SAVEDATA1000
launch game and talk to geralt

did not work for me. I found the fix for the grey sky falling all i did was quickly warped to wildspire wasted and back into Astera. Now when I trey to go to research base I instantly crash. So this fix doesnt work for all.

**Comment by PogopunkXIII** [comment]
> > OK I have the fix:
> 
> Save in research base, close the game
> backup SAVEDATA1000
> Open SAVEDATA1000 in the save editor
> Save file as unencrypted (.bin)
> Drag and drop unencrypted save file on GeraltFix.exe
> Open Fix.bin in the save editor
> Save as encrypted over the original SAVEDATA1000
> launch game and talk to geralt
> 
> did not work for me. I found the fix for the grey sky falling all i did was quickly warped to wildspire wasted and back into Astera. Now when I trey to go to research base I instantly crash. So this fix doesnt work for all.

did you backup your save before trying to apply the fix?

**Comment by AsteriskAmpersand** [comment]
That will only work in the old exe Shundere.
