### ISSUE TITLE
Slot selection not working properly

### ISSUE THREAD

**Issue by wecouldbedragons** [AsteriskAmpersand/MHW_Gerardo_Fix#2]
Whenever I try to call GerardoFix.exe with any slotnumber (even 1) as argument, it fails with an error. It executes perfectly fine when I call it without an argument, though, sadly I need to fix saveslot 2...

Traceback (most recent call last):
  File "E:\NPCFix\GerardoFix.py", line 19, in <module>
TypeError: unsupported operand type(s) for -: 'str' and 'int'
[6072] Failed to execute script GerardoFix

Thank you in advance!

**Comment by AsteriskAmpersand** [comment]
oh, lol need to cast before using, will fix later today.

**Comment by AsteriskAmpersand** [comment]
Should work fine now.
