### ISSUE TITLE
Accidentally used on wrong save slot.

### ISSUE THREAD

**Issue by HenryLin13** [AsteriskAmpersand/MHW_Gerardo_Fix#4]
My main character that had the problem was in Slot 2, I guess when putting in command to modify Slot 2 I did it wrong so it modified my Slot 1 instead. Now my alt character so far has been fine so I didn't think about it. But I tried doing the giant Kulu Yaku and it just black screens at cutscene part but the game is actually playable. Is there a way to reverse the Geralt fix? I would normally use the backup but this is roughly a month after I did the process and the character is fairly progressed after.

**Comment by AsteriskAmpersand** [comment]
From the README:
The fix is provided as is with no guarantee of working, it's unlikely I'll attempt to rewrite for every bizarre case there is as it's a pretty egregious blind patch.
